---
image: golang

services:
  database:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  cache:
    image: redis

script:
  - export WORKDIR=$GOPATH/src/github.com/gchaincl/ci
  - echo $WORKDIR